### PR TITLE
Edits from workshop discussion meeting

### PR DESCRIPTION
**Pull request by mblue9**

### CODE REVIEW

**Comment by mblue9** [comment]
Testing out the merged PR now, should I add `tidysc` as package here?
```   Quitting from lines 358-383 (tidytranscriptomics_case_study.Rmd) 
   Error: processing vignette 'tidytranscriptomics_case_study.Rmd' failed with diagnostics:
   there is no package called 'tidysc'
```

**Comment by stemangiola** [comment]
> Testing out the merged PR now, should I add `tidysc` as package here?
> 
> ```
>    Error: processing vignette 'tidytranscriptomics_case_study.Rmd' failed with diagnostics:
>    there is no package called 'tidysc'
> ```

I am incorporating the function now. I will push the changes very soon

**Comment by mblue9** [comment]
Ok great, one other thing I notice at the moment is that we still have some Seurat commands for the bit below in the vignette, are there Bioconductor equivalents we could use instead?

>It is then possible to perform analyses on these gamma delta T cells by simply chaining further commands, such as below.

```{r eval = FALSE}

sce_obj_gamma_delta |>

  # Reanalyse
  NormalizeData(assay="RNA") |>
  FindVariableFeatures( nfeatures = 100, assay="RNA") |>
  SplitObject(split.by = "file") |>
  RunFastMNN(assay="RNA") |>
  RunUMAP(reduction = "mnn", dims = 1:20) |>
  FindNeighbors( dims = 1:20, reduction = "mnn") |>
  FindClusters( resolution = 0.3)
```

**Comment by stemangiola** [comment]
I have the feeling we solved this problem with one of the BioC workshops. With BioC data reanalysis.

**Comment by mblue9** [comment]
Don't see it in iscb2022 one but maybe this rpharma2021 one https://tidytranscriptomics-workshops.github.io/rpharma2021_tidytranscriptomics/articles/tidytranscriptomics.html#part-2-single-cell-rna-sequencing-with-tidysinglecellexperiment-1?
If that's it are you able to pull out what commands we should include here?

**Comment by mblue9** [comment]
Besides above I think the main thing we need is a bit more explanation for the pseudobulk part on what's being done and the code as for prerequisites we only require basic tidyverse/single cell so some more text/comments e.g. on the steps and nest, map, map2, map_int would be good. If you could add a couple more comments I could flesh out text once the code runs (need above tidysc bit).

**Pull request merged**
