### PR TITLE
add pseudobulk. 

### PR DESCRIPTION
**Pull request by stemangiola**
@mblue9  There is an error because there must be some empty datasets for some cells, I have to check.

### CODE REVIEW

**Comment by stemangiola** [comment]
Hell @mblue9, I have added the code for pseudobulk analysis. Tomorrow I have a presentation, if you have some time today to curate my edits would be amazing. Tomorrow after the meeting, I will try to complete the workshop.

Thanks a lot.

**Comment by mblue9** [comment]
👍  I'll have a look today. One issue I see is the current actions fail is due to 
`Theme element `strip.clip` is not defined in the element hierarchy.`
Can we remove that? Otherwise we need to install that ggplot PR?

**Comment by stemangiola** [comment]
Sure we can drop

**Comment by mblue9** [comment]
Ok I'll drop that. I'll merge this into my PR and have a look through all.

**Pull request merged**
